### ISSUE TITLE
Performance Issues with ScrollView and Shelves

### ISSUE THREAD

**Issue by RobertArissen** [flexn-io/create#200]
We are in the process of transitioning from the old `flexn/sdk` to the new `flexn/create`. However, we are encountering an issue with performance when using shelves. We want to achieve the same effect as you did with carousels, where there is a long list of items. However, when we add multiple shelves, the `ScrollView` makes the app very slow.

How would you recommend solving this with your new setup? Specifically, how can we replace `ScrollView` with something like `FlashList` to ensure better performance, so it only renders what's necessary? With `ScrollView`, it loads all shelves at once, which is making the app lag. 

On the web environment, FlashList seems to work stacked vertically (like a ScrollView), but on AndroidTV this doesn't seem to work?

Any guidance or best practices would be greatly appreciated.

**Comment by aurimasmi** [comment]
If I understood your problem correctly you are trying to render a lot of carousels stacked vertically intro scrollview right?

If that's the case then slowliness is expected, because yes Scrollview does render everything at once regardless if items are out of viewport.

FlashList is not designed to work horizontally and vertically at the same time only one direction. I've never tried to make it work in such way but I would expect issues especially if your rails are not the same(size, styles etc).

My suggestions would be:

1. Set a limit of rails how much you want to render
2. Optimise your images to the size which would be very close to the one you need to render

By the way how does your rails looks like is it all has the same design? Technically then it could be recyclable also, but that's not implemented in `create` library
