### ISSUE TITLE
[Chromecast] Weird line on the top and weird version number on flexn/template

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/create#28]
rnv version: 0.36.1-canary.2
flexn template version: 0.16.0

How to repro:
1. Have app running on iOS or Android
2. Click cast button and cast to you selected device
3. Observe content on selected device -> weird line on the top and weird version number are visible
![PXL_20220211_093247713](https://user-images.githubusercontent.com/65670660/153580882-a0740a41-5d0e-4865-bee1-3dd884936d8d.jpg)

**Comment by locksten** [comment]
Wasn't able to reproduce the bar at the top with:
- rnv 0.36.1-canary.2
- flexn template v0.16.0
- [CastReceiver](https://play.google.com/store/apps/details?id=com.softmedia.receiver.castapp) / [AirScreen](https://play.google.com/store/apps/details?id=com.ionitech.airscreen), rather than a real tv

Did reproduce the version number in the top right, but is it not supposed to be there?

**Comment by pauliusguzas** [comment]
@locksten shouldn't the version number be like 0.17.0 or something?

**Comment by GabrieleKaceviciute** [comment]
Closing as this functionality was removed
